// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using OpenQA.Selenium.Edge;
using WebDriverManager.DriverConfigs.Impl;
using WebDriverManager.DriverConfigs;

[TestFixture]
public class DefaultSuiteTest
{
    private FirefoxDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        new WebDriverManager.DriverManager().SetUpDriver(new FirefoxConfig());
        driver = new FirefoxDriver();
        //driver = new FirefoxDriver();
        //js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        if (driver != null)
        {
            driver.Quit();     // Ends the browser session
            driver.Dispose();  // Properly disposes the driver
        }
    }
    [Test]
    public void t001()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
        //var quoteField = wait.Until(d =>
        //{
        //    var element = d.FindElement(By.Id("finalQuote"));
        //    return !string.IsNullOrEmpty(element.GetAttribute("value")) ? element : null;
        //});
        //string actualValue = quoteField.GetAttribute("value");
        //Assert.That(actualValue, Is.EqualTo("$4500"));

        //Assert.That(vars["id=finalQuote"].ToString(), Is.EqualTo("$4500"));
        String actualValue = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        ////Assert
        Assert.That(actualValue, Is.EqualTo("$4500"));
    }

    [Test]
    public void InsuranceQuote10_CustomTest_Exactly30WithDiscount()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string actualValue = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        Assert.That(actualValue, Is.EqualTo("$3285"));
    }

    [Test]
    public void InsuranceQuote11_CustomTest_AccidentsBoundary2()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).SendKeys("32");
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string actualValue = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        Assert.That(actualValue, Is.EqualTo("$3285"));
    }

    [Test]
    public void InsuranceQuote12_CustomTest_AccidentsBoundary3()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("3");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string actualValue = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        Assert.That(actualValue, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
    }

    [Test]
    public void InsuranceQuote13_CustomTest_InvalidPostalCodeLettersOnly()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("123456");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string postalError = driver.FindElement(By.Id("postalCode-error")).Text;
        Assert.That(postalError, Does.Contain("Postal Code must follow the pattern A1A 1A1"));
    }

    [Test]
    public void InsuranceQuote14_CustomTest_InvalidPhoneWithSpaces()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("123 123 1234");
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string phoneError = driver.FindElement(By.Id("phone-error")).Text;
        Assert.That(phoneError, Does.Contain("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }

    [Test]
    public void InsuranceQuote15_CustomTest_Age16With0Experience()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8173_A04/");
        driver.Manage().Window.Size = new System.Drawing.Size(822, 696);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Max");
        driver.FindElement(By.Id("lastName")).SendKeys("Danny");
        driver.FindElement(By.Id("address")).SendKeys("370 Schreyer");
        driver.FindElement(By.Id("city")).SendKeys("Milton");
        driver.FindElement(By.Id("postalCode")).SendKeys("L9T 7T2");
        driver.FindElement(By.Id("email")).SendKeys("shrestareddy82@gmail.com");
        driver.FindElement(By.Id("phone")).SendKeys("437-776-8774");
        driver.FindElement(By.Id("age")).SendKeys("16");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        string actualValue = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
        Assert.That(actualValue, Is.EqualTo("$6000"));
    }

}